include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_const_declarations
    - use_key_in_widget_builders
    - avoid_unnecessary_containers
    - prefer_final_locals
    - prefer_final_in_for_each
